name: Questions We Ask Ourselves
favicon: null
layout_spectrum: 0.6395840053446591
typography_spectrum: 0.5350169306620955
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.2919844533316791
  lightness: 0.49121314310468733
  saturation: 0.6135256662964821
  rhythmicContrast: 0.9979397356510162
purpose: []
